/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Fromted;

import Backend.Procesos;
import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author carlosrodriguez
 */
public class Archivo_Entrada extends javax.swing.JPanel {

    /**
     * Creates new form Solicitud
     */
    
    Procesos proceso=new Procesos();
    
    public Archivo_Entrada() {
        initComponents();
        jPanel1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton_ayuda = new javax.swing.JButton();
        boton_procesar = new javax.swing.JButton();

        setBackground(new java.awt.Color(228, 207, 154));
        setPreferredSize(new java.awt.Dimension(730, 490));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(228, 207, 154));
        jPanel1.setLayout(null);

        boton_ayuda.setBackground(new java.awt.Color(44, 68, 85));
        boton_ayuda.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        boton_ayuda.setForeground(new java.awt.Color(255, 255, 255));
        boton_ayuda.setText("Ayuda");
        boton_ayuda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_ayuda.setEnabled(true
        );
        boton_ayuda.setFocusCycleRoot(true);
        boton_ayuda.setFocusTraversalPolicyProvider(true);
        boton_ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_ayudaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_ayudaMouseExited(evt);
            }
        });
        boton_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ayudaActionPerformed(evt);
            }
        });
        jPanel1.add(boton_ayuda);
        boton_ayuda.setBounds(530, 460, 200, 30);

        boton_procesar.setBackground(new java.awt.Color(44, 68, 85));
        boton_procesar.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        boton_procesar.setForeground(new java.awt.Color(255, 255, 255));
        boton_procesar.setText("Procesar Archivo");
        boton_procesar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_procesar.setEnabled(true
        );
        boton_procesar.setFocusCycleRoot(true);
        boton_procesar.setFocusTraversalPolicyProvider(true);
        boton_procesar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_procesarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_procesarMouseExited(evt);
            }
        });
        boton_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_procesarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_procesar);
        boton_procesar.setBounds(270, 230, 200, 30);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 490);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_ayudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ayudaMouseEntered
        boton_ayuda.setBackground(Color.white);
        boton_ayuda.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_boton_ayudaMouseEntered

    private void boton_ayudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ayudaMouseExited
        boton_ayuda.setBackground(new java.awt.Color(44, 68, 85));
        boton_ayuda.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_boton_ayudaMouseExited

    private void boton_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ayudaActionPerformed

    }//GEN-LAST:event_boton_ayudaActionPerformed

    private void boton_procesarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_procesarMouseEntered
        boton_procesar.setBackground(Color.GREEN);
    }//GEN-LAST:event_boton_procesarMouseEntered

    private void boton_procesarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_procesarMouseExited
        boton_procesar.setBackground(new java.awt.Color(44, 68, 85));
    }//GEN-LAST:event_boton_procesarMouseExited

    private void boton_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_procesarActionPerformed
        proceso.Archivo(abrirSelectorDeArchivo());
    }//GEN-LAST:event_boton_procesarActionPerformed

    public static String abrirSelectorDeArchivo() {
        // Crear una instancia de JFileChooser
        JFileChooser fileChooser = new JFileChooser();
        
        // Mostrar el cuadro de diálogo para abrir un archivo
        int resultado = fileChooser.showOpenDialog(null);
        
        // Verificar si el usuario seleccionó un archivo
        if (resultado == JFileChooser.APPROVE_OPTION) {
            // Obtener el archivo seleccionado
            File archivoSeleccionado = fileChooser.getSelectedFile();
            // Devolver la dirección del archivo como una cadena
            return archivoSeleccionado.getAbsolutePath();
        } else {
            // Si el usuario cancela, devolver null o una cadena vacía
            return null;
        }
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_ayuda;
    private javax.swing.JButton boton_procesar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
