/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Fromted;

import Backend.Procesos;
import java.awt.Color;

/**
 *
 * @author carlosrodriguez
 */
public class Consulta extends javax.swing.JPanel {

    /**
     * Creates new form Solicitud
     */
    
    
    Procesos proceso=new Procesos();
    
    public Consulta() {
        initComponents();
        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton_ayuda = new javax.swing.JButton();
        No_tarjeta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        boton_procesar = new javax.swing.JButton();
        boton_cancelar = new javax.swing.JButton();
        boton_formulario = new javax.swing.JButton();
        boton_archivo_entrada = new javax.swing.JButton();

        setBackground(new java.awt.Color(228, 207, 154));
        setPreferredSize(new java.awt.Dimension(730, 490));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(228, 207, 154));
        jPanel1.setLayout(null);

        boton_ayuda.setBackground(new java.awt.Color(44, 68, 85));
        boton_ayuda.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        boton_ayuda.setForeground(new java.awt.Color(255, 255, 255));
        boton_ayuda.setText("Ayuda");
        boton_ayuda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_ayuda.setEnabled(true
        );
        boton_ayuda.setFocusCycleRoot(true);
        boton_ayuda.setFocusTraversalPolicyProvider(true);
        boton_ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_ayudaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_ayudaMouseExited(evt);
            }
        });
        boton_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ayudaActionPerformed(evt);
            }
        });
        jPanel1.add(boton_ayuda);
        boton_ayuda.setBounds(530, 460, 200, 30);

        No_tarjeta.setBackground(new java.awt.Color(158, 144, 100));
        No_tarjeta.setFont(new java.awt.Font("Comic Sans MS", 3, 15)); // NOI18N
        No_tarjeta.setForeground(new java.awt.Color(255, 255, 255));
        No_tarjeta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        No_tarjeta.setToolTipText("");
        No_tarjeta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(No_tarjeta);
        No_tarjeta.setBounds(230, 180, 300, 30);

        jLabel2.setBackground(new java.awt.Color(20, 12, 77));
        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 49, 74));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("No. Tarjeta:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 190, 130, 20);

        boton_procesar.setBackground(new java.awt.Color(44, 68, 85));
        boton_procesar.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        boton_procesar.setForeground(new java.awt.Color(255, 255, 255));
        boton_procesar.setText("Procesar Consulta ");
        boton_procesar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_procesar.setEnabled(true
        );
        boton_procesar.setFocusCycleRoot(true);
        boton_procesar.setFocusTraversalPolicyProvider(true);
        boton_procesar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_procesarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_procesarMouseExited(evt);
            }
        });
        boton_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_procesarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_procesar);
        boton_procesar.setBounds(270, 440, 200, 30);

        boton_cancelar.setBackground(new java.awt.Color(44, 68, 85));
        boton_cancelar.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        boton_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        boton_cancelar.setText("Cancelar");
        boton_cancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_cancelar.setEnabled(true
        );
        boton_cancelar.setFocusCycleRoot(true);
        boton_cancelar.setFocusTraversalPolicyProvider(true);
        boton_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_cancelarMouseExited(evt);
            }
        });
        boton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_cancelar);
        boton_cancelar.setBounds(0, 420, 200, 30);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 490);

        boton_formulario.setBackground(new java.awt.Color(44, 68, 85));
        boton_formulario.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        boton_formulario.setForeground(new java.awt.Color(255, 255, 255));
        boton_formulario.setText("formulario");
        boton_formulario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_formulario.setEnabled(true
        );
        boton_formulario.setFocusCycleRoot(true);
        boton_formulario.setFocusTraversalPolicyProvider(true);
        boton_formulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_formularioActionPerformed(evt);
            }
        });
        add(boton_formulario);
        boton_formulario.setBounds(215, 170, 300, 25);

        boton_archivo_entrada.setBackground(new java.awt.Color(44, 68, 85));
        boton_archivo_entrada.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        boton_archivo_entrada.setForeground(new java.awt.Color(255, 255, 255));
        boton_archivo_entrada.setText("Archivo de entrada");
        boton_archivo_entrada.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_archivo_entrada.setEnabled(true
        );
        boton_archivo_entrada.setFocusCycleRoot(true);
        boton_archivo_entrada.setFocusTraversalPolicyProvider(true);
        boton_archivo_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_archivo_entradaActionPerformed(evt);
            }
        });
        add(boton_archivo_entrada);
        boton_archivo_entrada.setBounds(215, 280, 300, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_archivo_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_archivo_entradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_archivo_entradaActionPerformed

    private void boton_formularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_formularioActionPerformed
        jPanel1.setVisible(true);
        boton_archivo_entrada.setVisible(false);
        boton_formulario.setVisible(false);
    }//GEN-LAST:event_boton_formularioActionPerformed

    private void boton_ayudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ayudaMouseEntered
        boton_ayuda.setBackground(Color.white);
        boton_ayuda.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_boton_ayudaMouseEntered

    private void boton_ayudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ayudaMouseExited
        boton_ayuda.setBackground(new java.awt.Color(44, 68, 85));
        boton_ayuda.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_boton_ayudaMouseExited

    private void boton_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ayudaActionPerformed

    }//GEN-LAST:event_boton_ayudaActionPerformed

    private void boton_procesarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_procesarMouseEntered
        boton_procesar.setBackground(Color.GREEN);
    }//GEN-LAST:event_boton_procesarMouseEntered

    private void boton_procesarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_procesarMouseExited
        boton_procesar.setBackground(new java.awt.Color(44, 68, 85));
    }//GEN-LAST:event_boton_procesarMouseExited

    private void boton_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_procesarActionPerformed
        proceso.consulta(No_tarjeta.getText());
    }//GEN-LAST:event_boton_procesarActionPerformed

    private void boton_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_cancelarMouseEntered

        boton_cancelar.setBackground(Color.red);
    }//GEN-LAST:event_boton_cancelarMouseEntered

    private void boton_cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_cancelarMouseExited
        boton_cancelar.setBackground(new java.awt.Color(44, 68, 85));
    }//GEN-LAST:event_boton_cancelarMouseExited

    private void boton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cancelarActionPerformed
        jPanel1.setVisible(false);
        boton_archivo_entrada.setVisible(true);
        boton_formulario.setVisible(true);
        reiniciar_formulario();
    }//GEN-LAST:event_boton_cancelarActionPerformed

    
    void reiniciar_formulario(){
       
        No_tarjeta.setText("");
     
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField No_tarjeta;
    private javax.swing.JButton boton_archivo_entrada;
    private javax.swing.JButton boton_ayuda;
    private javax.swing.JButton boton_cancelar;
    private javax.swing.JButton boton_formulario;
    private javax.swing.JButton boton_procesar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
