package Fromted;

import Backend.Procesos;
import Backend.Listado_De_Estado_Cuenta;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.sql.Date;
import java.util.List;

import javax.swing.JButton;

import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlosrodriguez
 */
public class Listado_De_Estados_De_Cuenta extends javax.swing.JPanel {

    /**
     * Creates new form Solicitud
     */
    Procesos proceso = new Procesos();

    private JTable table;
    private JScrollPane scrollPane;

    public Listado_De_Estados_De_Cuenta() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        st = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nt = new javax.swing.JLabel();
        tt = new javax.swing.JLabel();
        nc = new javax.swing.JLabel();
        dc = new javax.swing.JLabel();
        mt = new javax.swing.JLabel();
        i = new javax.swing.JLabel();
        boton_ayuda = new javax.swing.JButton();
        boton_procesar = new javax.swing.JButton();
        borrar_filtros = new javax.swing.JButton();
        Tipo = new javax.swing.JComboBox<>();
        saldo = new javax.swing.JTextField();
        numeroTarjeta = new javax.swing.JTextField();
        interes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jFrame1.setBackground(new java.awt.Color(255, 255, 254));
        jFrame1.setMinimumSize(new java.awt.Dimension(800, 600));
        jFrame1.setName("ESTADO DE CUENTA"); // NOI18N
        jFrame1.setResizable(false);
        jFrame1.getContentPane().setLayout(null);

        st.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jFrame1.getContentPane().add(st);
        st.setBounds(170, 530, 160, 20);

        jLabel7.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("NOMBRE CLIENTE :");
        jFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 110, 160, 20);

        jLabel8.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("NÚMERO TARJETA:");
        jFrame1.getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 50, 160, 20);

        jLabel9.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("MONTO TOTAL: ");
        jFrame1.getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 470, 140, 20);

        jLabel10.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("TIPO TARJETA:");
        jFrame1.getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 80, 160, 20);

        jLabel11.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 102));
        jLabel11.setText("DIRECCION CLIENTE:");
        jFrame1.getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 140, 190, 20);

        jLabel12.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 102));
        jLabel12.setText("SALDO TOTAL:");
        jFrame1.getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 530, 120, 20);

        jLabel13.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 102));
        jLabel13.setText("INTERESES:");
        jFrame1.getContentPane().add(jLabel13);
        jLabel13.setBounds(40, 500, 120, 20);

        nt.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jFrame1.getContentPane().add(nt);
        nt.setBounds(210, 50, 160, 20);

        tt.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jFrame1.getContentPane().add(tt);
        tt.setBounds(180, 80, 160, 20);

        nc.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jFrame1.getContentPane().add(nc);
        nc.setBounds(210, 110, 160, 20);

        dc.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jFrame1.getContentPane().add(dc);
        dc.setBounds(220, 140, 160, 20);

        mt.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jFrame1.getContentPane().add(mt);
        mt.setBounds(170, 470, 160, 20);

        i.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jFrame1.getContentPane().add(i);
        i.setBounds(150, 500, 160, 20);

        setBackground(new java.awt.Color(228, 207, 154));
        setPreferredSize(new java.awt.Dimension(730, 490));
        setLayout(null);

        boton_ayuda.setBackground(new java.awt.Color(44, 68, 85));
        boton_ayuda.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        boton_ayuda.setForeground(new java.awt.Color(255, 255, 255));
        boton_ayuda.setText("Ayuda");
        boton_ayuda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_ayuda.setEnabled(true
        );
        boton_ayuda.setFocusCycleRoot(true);
        boton_ayuda.setFocusTraversalPolicyProvider(true);
        boton_ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_ayudaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_ayudaMouseExited(evt);
            }
        });
        boton_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ayudaActionPerformed(evt);
            }
        });
        add(boton_ayuda);
        boton_ayuda.setBounds(0, 460, 60, 30);

        boton_procesar.setBackground(new java.awt.Color(44, 68, 85));
        boton_procesar.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        boton_procesar.setForeground(new java.awt.Color(255, 255, 255));
        boton_procesar.setText("Procesar Busqueda");
        boton_procesar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_procesar.setEnabled(true
        );
        boton_procesar.setFocusCycleRoot(true);
        boton_procesar.setFocusTraversalPolicyProvider(true);
        boton_procesar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_procesarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_procesarMouseExited(evt);
            }
        });
        boton_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_procesarActionPerformed(evt);
            }
        });
        add(boton_procesar);
        boton_procesar.setBounds(0, 380, 150, 30);

        borrar_filtros.setBackground(new java.awt.Color(44, 68, 85));
        borrar_filtros.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        borrar_filtros.setForeground(new java.awt.Color(255, 255, 255));
        borrar_filtros.setText("Borrar Filtros");
        borrar_filtros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        borrar_filtros.setEnabled(true
        );
        borrar_filtros.setFocusCycleRoot(true);
        borrar_filtros.setFocusTraversalPolicyProvider(true);
        borrar_filtros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrar_filtrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrar_filtrosMouseExited(evt);
            }
        });
        borrar_filtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar_filtrosActionPerformed(evt);
            }
        });
        add(borrar_filtros);
        borrar_filtros.setBounds(0, 420, 120, 30);

        Tipo.setBackground(new java.awt.Color(158, 144, 100));
        Tipo.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        Tipo.setForeground(new java.awt.Color(255, 255, 255));
        Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "NACIONAL", "REGIONAL", "INTERNACIONAL" }));
        add(Tipo);
        Tipo.setBounds(450, 440, 180, 26);
        add(saldo);
        saldo.setBounds(180, 440, 140, 24);

        numeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTarjetaActionPerformed(evt);
            }
        });
        add(numeroTarjeta);
        numeroTarjeta.setBounds(380, 400, 290, 24);
        add(interes);
        interes.setBounds(180, 400, 140, 24);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Interes mayor a ...");
        add(jLabel1);
        jLabel1.setBounds(190, 380, 130, 18);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Saldo mayor a...");
        add(jLabel2);
        jLabel2.setBounds(190, 470, 130, 20);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Numero de Tarjeta");
        add(jLabel3);
        jLabel3.setBounds(460, 380, 140, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_ayudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ayudaMouseEntered
        boton_ayuda.setBackground(Color.white);
        boton_ayuda.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_boton_ayudaMouseEntered

    private void boton_ayudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ayudaMouseExited
        boton_ayuda.setBackground(new java.awt.Color(44, 68, 85));
        boton_ayuda.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_boton_ayudaMouseExited

    private void boton_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ayudaActionPerformed

    }//GEN-LAST:event_boton_ayudaActionPerformed

    private void boton_procesarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_procesarMouseEntered
        boton_procesar.setBackground(Color.GREEN);
    }//GEN-LAST:event_boton_procesarMouseEntered

    private void boton_procesarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_procesarMouseExited
        boton_procesar.setBackground(new java.awt.Color(44, 68, 85));
    }//GEN-LAST:event_boton_procesarMouseExited

    private void boton_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_procesarActionPerformed
        String tipo = (String) Tipo.getSelectedItem();

        proceso.ListadoEstadosCuentas(tipo, interes.getText(), saldo.getText(), numeroTarjeta.getText());

        mostrarDatos();
    }//GEN-LAST:event_boton_procesarActionPerformed

    private void borrar_filtrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrar_filtrosMouseEntered

        borrar_filtros.setBackground(Color.red);
    }//GEN-LAST:event_borrar_filtrosMouseEntered

    private void borrar_filtrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrar_filtrosMouseExited
        borrar_filtros.setBackground(new java.awt.Color(44, 68, 85));
    }//GEN-LAST:event_borrar_filtrosMouseExited

    private void borrar_filtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar_filtrosActionPerformed

        reiniciar_formulario();
    }//GEN-LAST:event_borrar_filtrosActionPerformed

    private void numeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroTarjetaActionPerformed
    /**
     * Muestra los botones correspondientes a las tarjetas de crédito en un
     * JScrollPane. Cada botón representa una tarjeta de crédito y al ser
     * presionado actualiza la vista del estado de cuenta.
     */
    public void mostrarDatos() {
        // Crear un panel con GridLayout para contener los botones verticalmente
        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridLayout(0, 1)); // Organiza los botones verticalmente en una columna

        // Eliminar JScrollPane existente, si hay alguno
        for (Component comp : getComponents()) {
            if (comp instanceof JScrollPane) {
                remove(comp);
            }
        }

        // Tamaño deseado para los botones
        Dimension botonSize = new Dimension(700, 20); // Ancho fijo y altura de 20 píxeles

        // Espacio entre botones
        int espacioEntreBotones = 5;

        // Crear un JScrollPane con el panel de botones
        JScrollPane scrollPane = new JScrollPane(buttonPanel);
        scrollPane.setBounds(5, 5, 720, 365); // Establece la posición y tamaño del JScrollPane
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS); // Siempre mostrar la barra de desplazamiento vertical
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER); // No permitir desplazamiento horizontal

        // Obtener listas de tarjetas
        List<String> numeroTarjetas = Listado_De_Estado_Cuenta.getNumeroTarjetas();
        List<String> tipoTarjetas = Listado_De_Estado_Cuenta.getTipoTarjetas();

        // Agregar botones al panel
        for (int i = 0; i < numeroTarjetas.size(); i++) {
            JButton button = new JButton(numeroTarjetas.get(i) + "|" + tipoTarjetas.get(i));
            button.setPreferredSize(botonSize); // Establece el tamaño preferido del botón

            // Agregar un ActionListener para cada botón
            final int botonNumero = i; // Variable final para usar dentro del ActionListener
            button.addActionListener(e -> {
                // Acción a realizar cuando se presiona el botón
                String numeroTarjeta = button.getText();
                if (numeroTarjeta.length() > 16) {
                    numeroTarjeta = numeroTarjeta.substring(0, 16); // Obtener los primeros 16 caracteres
                }

                // Llamar al método con el texto truncado
                proceso.datosEstadoCuenta(numeroTarjeta);
                mostrarEstado();
            });

            buttonPanel.add(button);
        }

        // Establecer el tamaño preferido del panel de botones
        int panelHeight = 20 * numeroTarjetas.size() + espacioEntreBotones * (numeroTarjetas.size() - 1); // Ajusta el tamaño para permitir el desplazamiento
        buttonPanel.setPreferredSize(new Dimension(scrollPane.getViewport().getWidth(), panelHeight)); // Usa el ancho del viewport del JScrollPane

        // Configurar el layout del panel principal para null
        setLayout(null);
        add(scrollPane);

        // Actualizar el diseño del panel para que se reflejen los cambios
        revalidate();
        repaint();
    }

    /**
     * Muestra el estado de cuenta en un JFrame, actualizando los campos de
     * texto y mostrando una tabla con los movimientos.
     */
    public void mostrarEstado() {
        // Actualiza los campos de texto con los datos de la tarjeta
        List<String> datos = Listado_De_Estado_Cuenta.getDatos();
        List<String> datosNumericos = Listado_De_Estado_Cuenta.getDatosNumericos();

        nt.setText(datos.get(0));
        tt.setText(datos.get(1));
        nc.setText(datos.get(2));
        dc.setText(datos.get(3));
        mt.setText(datosNumericos.get(0));
        i.setText(datosNumericos.get(1));
        st.setText(datosNumericos.get(2));

        // Muestra el JFrame
        jFrame1.setVisible(true);
        jFrame1.setLocationRelativeTo(null); // Centra el JFrame en la pantalla

        // Elimina el JScrollPane que contiene la tabla, si existe
        for (Component comp : jFrame1.getContentPane().getComponents()) {
            if (comp instanceof JScrollPane) {
                jFrame1.getContentPane().remove(comp);
            }
        }

        // Crear el arreglo de datos para la tabla
        List<Date> fecha = Listado_De_Estado_Cuenta.getFecha();
        List<String> tipoMovimiento = Listado_De_Estado_Cuenta.getTipoMovimiento();
        List<String> descripcion = Listado_De_Estado_Cuenta.getDescripcion();
        List<String> establecimieto = Listado_De_Estado_Cuenta.getEstablecimieto();
        List<String> montos = Listado_De_Estado_Cuenta.getMontos();

        Object[][] datosTabla = new Object[fecha.size()][5];
        for (int i = 0; i < fecha.size(); i++) {
            datosTabla[i][0] = fecha.get(i);
            datosTabla[i][1] = tipoMovimiento.get(i);
            datosTabla[i][2] = descripcion.get(i);
            datosTabla[i][3] = establecimieto.get(i);
            datosTabla[i][4] = montos.get(i);
        }

        // Columnas de la tabla
        String[] columnas = {"FECHA", "TIPO DE MOVIMIENTO", "DESCRIPCIÓN", "ESTABLECIMIENTO", "MONTO"};

        // Crear el modelo de la tabla y la tabla
        DefaultTableModel model = new DefaultTableModel(datosTabla, columnas);
        JTable table = new JTable(model);

        // Colocar la tabla en un JScrollPane
        JScrollPane tableScrollPane = new JScrollPane(table);
        tableScrollPane.setBounds(10, 160, 780, 300);

        // Agregar el JScrollPane al JFrame
        jFrame1.getContentPane().add(tableScrollPane);

        // Asegurarse de que el panel se dibuje correctamente
        jFrame1.revalidate();
        jFrame1.repaint();
    }

    void reiniciar_formulario() {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Tipo;
    private javax.swing.JButton borrar_filtros;
    private javax.swing.JButton boton_ayuda;
    private javax.swing.JButton boton_procesar;
    private javax.swing.JLabel dc;
    private javax.swing.JLabel i;
    private javax.swing.JTextField interes;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel mt;
    private javax.swing.JLabel nc;
    private javax.swing.JLabel nt;
    private javax.swing.JTextField numeroTarjeta;
    private javax.swing.JTextField saldo;
    private javax.swing.JLabel st;
    private javax.swing.JLabel tt;
    // End of variables declaration//GEN-END:variables
}
