/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Fromted;

import Backend.Procesos;
import java.awt.Color;

/**
 *
 * @author carlosrodriguez
 */
public class Solicitud extends javax.swing.JPanel {

    /**
     * Creates new form Solicitud
     */
    
    Procesos proceso=new Procesos();
    
    public Solicitud() {
        initComponents();
        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        direccion = new javax.swing.JTextField();
        tipoCuenta = new javax.swing.JComboBox<>();
        boton_ayuda = new javax.swing.JButton();
        numero_solicitud = new javax.swing.JTextField();
        salario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        boton_procesar = new javax.swing.JButton();
        boton_cancelar = new javax.swing.JButton();
        fecha = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        boton_formulario = new javax.swing.JButton();
        boton_archivo_entrada = new javax.swing.JButton();

        setBackground(new java.awt.Color(228, 207, 154));
        setPreferredSize(new java.awt.Dimension(730, 490));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(228, 207, 154));
        jPanel1.setLayout(null);

        direccion.setBackground(new java.awt.Color(158, 144, 100));
        direccion.setFont(new java.awt.Font("Comic Sans MS", 3, 15)); // NOI18N
        direccion.setForeground(new java.awt.Color(255, 255, 255));
        direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        direccion.setToolTipText("");
        direccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(direccion);
        direccion.setBounds(420, 230, 280, 30);

        tipoCuenta.setBackground(new java.awt.Color(158, 144, 100));
        tipoCuenta.setForeground(new java.awt.Color(255, 255, 255));
        tipoCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Cuenta ...", "NACIONAL", "REGIONAL", "INTERNACIONAL" }));
        tipoCuenta.setToolTipText("");
        tipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(tipoCuenta);
        tipoCuenta.setBounds(110, 140, 180, 32);

        boton_ayuda.setBackground(new java.awt.Color(44, 68, 85));
        boton_ayuda.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        boton_ayuda.setForeground(new java.awt.Color(255, 255, 255));
        boton_ayuda.setText("Ayuda");
        boton_ayuda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_ayuda.setEnabled(true
        );
        boton_ayuda.setFocusCycleRoot(true);
        boton_ayuda.setFocusTraversalPolicyProvider(true);
        boton_ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_ayudaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_ayudaMouseExited(evt);
            }
        });
        boton_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ayudaActionPerformed(evt);
            }
        });
        jPanel1.add(boton_ayuda);
        boton_ayuda.setBounds(530, 460, 200, 30);

        numero_solicitud.setBackground(new java.awt.Color(158, 144, 100));
        numero_solicitud.setFont(new java.awt.Font("Comic Sans MS", 3, 15)); // NOI18N
        numero_solicitud.setForeground(new java.awt.Color(255, 255, 255));
        numero_solicitud.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numero_solicitud.setToolTipText("");
        numero_solicitud.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(numero_solicitud);
        numero_solicitud.setBounds(420, 50, 280, 30);

        salario.setBackground(new java.awt.Color(158, 144, 100));
        salario.setFont(new java.awt.Font("Comic Sans MS", 3, 15)); // NOI18N
        salario.setForeground(new java.awt.Color(255, 255, 255));
        salario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        salario.setToolTipText("");
        salario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(salario);
        salario.setBounds(110, 230, 180, 30);

        jLabel1.setBackground(new java.awt.Color(20, 12, 77));
        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 49, 74));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Direccion:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 240, 140, 18);

        jLabel2.setBackground(new java.awt.Color(20, 12, 77));
        jLabel2.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 49, 74));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("No. Solicitud:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 60, 110, 20);

        jLabel3.setBackground(new java.awt.Color(20, 12, 77));
        jLabel3.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 49, 74));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fecha:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 140, 18);

        jLabel4.setBackground(new java.awt.Color(20, 12, 77));
        jLabel4.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 49, 74));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 150, 210, 20);

        jLabel5.setBackground(new java.awt.Color(20, 12, 77));
        jLabel5.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 49, 74));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Salario:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 240, 130, 18);

        boton_procesar.setBackground(new java.awt.Color(44, 68, 85));
        boton_procesar.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        boton_procesar.setForeground(new java.awt.Color(255, 255, 255));
        boton_procesar.setText("Procesar Solicitud");
        boton_procesar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_procesar.setEnabled(true
        );
        boton_procesar.setFocusCycleRoot(true);
        boton_procesar.setFocusTraversalPolicyProvider(true);
        boton_procesar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_procesarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_procesarMouseExited(evt);
            }
        });
        boton_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_procesarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_procesar);
        boton_procesar.setBounds(270, 440, 200, 30);

        boton_cancelar.setBackground(new java.awt.Color(44, 68, 85));
        boton_cancelar.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        boton_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        boton_cancelar.setText("Cancelar");
        boton_cancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_cancelar.setEnabled(true
        );
        boton_cancelar.setFocusCycleRoot(true);
        boton_cancelar.setFocusTraversalPolicyProvider(true);
        boton_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_cancelarMouseExited(evt);
            }
        });
        boton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_cancelar);
        boton_cancelar.setBounds(0, 420, 200, 30);

        fecha.setBackground(new java.awt.Color(158, 144, 100));
        fecha.setFont(new java.awt.Font("Comic Sans MS", 3, 15)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha.setToolTipText("");
        fecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fecha.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        fecha.setEnabled(false);
        jPanel1.add(fecha);
        fecha.setBounds(110, 50, 180, 30);

        nombre.setBackground(new java.awt.Color(158, 144, 100));
        nombre.setFont(new java.awt.Font("Comic Sans MS", 3, 15)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre.setToolTipText("");
        nombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(nombre);
        nombre.setBounds(420, 140, 280, 30);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 490);

        boton_formulario.setBackground(new java.awt.Color(44, 68, 85));
        boton_formulario.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        boton_formulario.setForeground(new java.awt.Color(255, 255, 255));
        boton_formulario.setText("formulario");
        boton_formulario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_formulario.setEnabled(true
        );
        boton_formulario.setFocusCycleRoot(true);
        boton_formulario.setFocusTraversalPolicyProvider(true);
        boton_formulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_formularioActionPerformed(evt);
            }
        });
        add(boton_formulario);
        boton_formulario.setBounds(215, 170, 300, 25);

        boton_archivo_entrada.setBackground(new java.awt.Color(44, 68, 85));
        boton_archivo_entrada.setFont(new java.awt.Font("Century Schoolbook L", 2, 15)); // NOI18N
        boton_archivo_entrada.setForeground(new java.awt.Color(255, 255, 255));
        boton_archivo_entrada.setText("Archivo de entrada");
        boton_archivo_entrada.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_archivo_entrada.setEnabled(true
        );
        boton_archivo_entrada.setFocusCycleRoot(true);
        boton_archivo_entrada.setFocusTraversalPolicyProvider(true);
        boton_archivo_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_archivo_entradaActionPerformed(evt);
            }
        });
        add(boton_archivo_entrada);
        boton_archivo_entrada.setBounds(215, 280, 300, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_archivo_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_archivo_entradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_archivo_entradaActionPerformed

    private void boton_formularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_formularioActionPerformed
        jPanel1.setVisible(true);
        fecha.setText(proceso.fechaActual());
        boton_archivo_entrada.setVisible(false);
        boton_formulario.setVisible(false);
    }//GEN-LAST:event_boton_formularioActionPerformed

    private void boton_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ayudaActionPerformed
        
    }//GEN-LAST:event_boton_ayudaActionPerformed

    private void tipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoCuentaActionPerformed

    private void boton_ayudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ayudaMouseEntered
            boton_ayuda.setBackground(Color.white);
            boton_ayuda.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_boton_ayudaMouseEntered

    private void boton_ayudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ayudaMouseExited
        boton_ayuda.setBackground(new java.awt.Color(44, 68, 85));
        boton_ayuda.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_boton_ayudaMouseExited

    private void boton_procesarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_procesarMouseEntered
        boton_procesar.setBackground(Color.GREEN);
    }//GEN-LAST:event_boton_procesarMouseEntered

    private void boton_procesarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_procesarMouseExited
        boton_procesar.setBackground(new java.awt.Color(44, 68, 85));
    }//GEN-LAST:event_boton_procesarMouseExited

    private void boton_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_procesarActionPerformed
      
        String tipo=(String) tipoCuenta.getSelectedItem();
        proceso.Procesar_Solicitud(Integer.parseInt(numero_solicitud.getText()), fecha.getText(),tipo, nombre.getText(),Double.valueOf(salario.getText()), direccion.getText());
        jPanel1.setVisible(false);
        boton_archivo_entrada.setVisible(true);
        boton_formulario.setVisible(true);
        reiniciar_formulario();
    }//GEN-LAST:event_boton_procesarActionPerformed

    private void boton_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_cancelarMouseEntered
       
        boton_cancelar.setBackground(Color.red);
    }//GEN-LAST:event_boton_cancelarMouseEntered

    private void boton_cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_cancelarMouseExited
         boton_cancelar.setBackground(new java.awt.Color(44, 68, 85));
    }//GEN-LAST:event_boton_cancelarMouseExited

    private void boton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cancelarActionPerformed
        jPanel1.setVisible(false);
        boton_archivo_entrada.setVisible(true);
        boton_formulario.setVisible(true);
        reiniciar_formulario();
    }//GEN-LAST:event_boton_cancelarActionPerformed

    void reiniciar_formulario(){
        direccion.setText("");
        nombre.setText("");
        fecha.setText("");
        numero_solicitud.setText("");
        salario.setText("");
    
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_archivo_entrada;
    private javax.swing.JButton boton_ayuda;
    private javax.swing.JButton boton_cancelar;
    private javax.swing.JButton boton_formulario;
    private javax.swing.JButton boton_procesar;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numero_solicitud;
    private javax.swing.JTextField salario;
    private javax.swing.JComboBox<String> tipoCuenta;
    // End of variables declaration//GEN-END:variables
}
